// Auto-generated by fetch_channel_thumbnails.py
// uploader 이름 → YouTube 채널 프로필 이미지 URL

const channelProfiles = {
  "MBN Entertainment": "https://yt3.ggpht.com/bhOSzFv7m__nY8l1piCDgaC-rcqe5PhCja1k4Dv5fKdfkRB554aRHzgkUvD5mNNnN0HfYaujRg=s240-c-k-c0x00ffffff-no-rj",
  "STUDIO JJ [스튜디오 제이제이]": "https://yt3.ggpht.com/PJlqB7oQUHdVISII_wENiiFOSzddDLC0--qDY6ZiWKt5k9abpFm9x5km-GfNvhuGJ44wEf2csg=s240-c-k-c0x00ffffff-no-rj",
  "강레오 걍레오": "https://yt3.ggpht.com/iY-bHRyOnjDh0X4jHW81JDQyaqvZbGYC6zb5ZZvsNI6LrVbbU_jcSitJ6sJ-WPFZ6A3MpMCVxQ=s240-c-k-c0x00ffffff-no-rj",
  "미뇨끼": "https://yt3.ggpht.com/Z9sRLb8U5gT62o6L7tbj6QlpIDDQ2EJsZyzp4MUC_wC0vEw7xQWn2ntl2DOtCr6eJNDa6_-Ijw=s240-c-k-c0x00ffffff-no-rj",
  "셰프호윤 Chef Hoyoon": "https://yt3.ggpht.com/mS-RaHIl9dFMh4AJ4qP7wBbdR7tFnPjMxq4IN8ipjzYAGLpLZGyFYKknc3pX4ClBvQZbdJPAfg=s240-c-k-c0x00ffffff-no-rj",
  "한신희": "https://yt3.ggpht.com/wMZgXsraUWw9dZyPpbmd13nnYa5ItI27oPvYPtco7j2QWSWHEwdhhG2XUyzUEG7DpvCr6MwI-w=s240-c-k-c0x00ffffff-no-rj",
};

export default channelProfiles;