// Auto-generated by fetch_channel_thumbnails.py
// uploader 이름 → YouTube 채널 프로필 이미지 URL

const channelProfiles = {
  "MBN Entertainment": "https://yt3.ggpht.com/bhOSzFv7m__nY8l1piCDgaC-rcqe5PhCja1k4Dv5fKdfkRB554aRHzgkUvD5mNNnN0HfYaujRg=s240-c-k-c0x00ffffff-no-rj",
  "STUDIO JJ [스튜디오 제이제이]": "https://yt3.ggpht.com/PJlqB7oQUHdVISII_wENiiFOSzddDLC0--qDY6ZiWKt5k9abpFm9x5km-GfNvhuGJ44wEf2csg=s240-c-k-c0x00ffffff-no-rj",
  "강레오 걍레오": "https://yt3.ggpht.com/iY-bHRyOnjDh0X4jHW81JDQyaqvZbGYC6zb5ZZvsNI6LrVbbU_jcSitJ6sJ-WPFZ6A3MpMCVxQ=s240-c-k-c0x00ffffff-no-rj",
  "미뇨끼": "https://yt3.ggpht.com/Z9sRLb8U5gT62o6L7tbj6QlpIDDQ2EJsZyzp4MUC_wC0vEw7xQWn2ntl2DOtCr6eJNDa6_-Ijw=s240-c-k-c0x00ffffff-no-rj",
  "셰프호윤 Chef Hoyoon": "https://yt3.ggpht.com/mS-RaHIl9dFMh4AJ4qP7wBbdR7tFnPjMxq4IN8ipjzYAGLpLZGyFYKknc3pX4ClBvQZbdJPAfg=s240-c-k-c0x00ffffff-no-rj",
  "한신희": "https://yt3.ggpht.com/wMZgXsraUWw9dZyPpbmd13nnYa5ItI27oPvYPtco7j2QWSWHEwdhhG2XUyzUEG7DpvCr6MwI-w=s240-c-k-c0x00ffffff-no-rj",
  "공부왕찐천재 홍진경": "https://yt3.ggpht.com/ytc/AIdro_mXJxSXiJa2E26VH10eCDts0qd7FQszSNbx9tWxpHkD4w=s240-c-k-c0x00ffffff-no-rj",
  "이민정 MJ": "https://yt3.ggpht.com/ziRXDHkr_0F7dw_zazv6msvTN14FBxKT2MbmwxZltnjMcR_Mu6Jlv4icC3NL4wnTVnZiuVjG6A=s240-c-k-c0x00ffffff-no-rj",
  "Ben Maxwell": "https://yt3.ggpht.com/7Z_r2B6EANYsyamuB8u7sQvFJ0WpAlzX7aMxURAKju9YhQT8ez1XDFLoLTknrXPYdLhKQdgXzw=s240-c-k-c0x00ffffff-no-rj",
  "김밀란": "https://yt3.ggpht.com/9HOr5dWJKbDCdTnmFXgBpVjn7I0Im-j-qrKIDJ-DJ9Vu5UFyTAuOM1kGB_Qm9OZzCjcFDayo0g=s240-c-k-c0x00ffffff-no-rj",
  "백종원 PAIK JONG WON": "https://yt3.ggpht.com/tVvGKye5hDl70LaxrUsJBfm-rE9RES7bJDxSrjyO-vQDVb5EUJvUJefjUJ0dp-ixLIkrDYVX4A=s240-c-k-c0x00ffffff-no-rj",
  "철가방요리사": "https://yt3.ggpht.com/DxJEY_PJp9EGyHmzTBLTfBaabyb-zcSk8F9HlJj08b0bLUg06lCryQKSeqgfZE_BQYUjsLzAUg=s240-c-k-c0x00ffffff-no-rj",
};

export default channelProfiles;