const chefConfig = {
  "이태리 파브리 Italy Fabri": {
    slug: "fabri",
    displayName: "이태리 파브리",
    heroTitle: "파브리의 레시피\n재료로 바로 찾기",
    heroSubtitle: "내 재료로 파브리의 요리를 찾아보세요!",
    heroTitleEn: "Fabri's Recipes\nFind by Ingredients",
    heroSubtitleEn: "Find Fabri's dishes with what you have!",
    youtubeUrl: "https://www.youtube.com/@italyfabri",
    instagramUrl: "https://www.instagram.com/fabrilicious/",
  },
  "셰프호윤 Chef Hoyoon": {
    slug: "hoyoon",
    displayName: "셰프호윤",
    heroTitle: "셰프호윤의 레시피\n재료로 바로 찾기",
    heroSubtitle: "내 재료로 셰프호윤의 요리를 찾아보세요!",
    heroTitleEn: "Chef Hoyun's Recipes\nFind by Ingredients",
    heroSubtitleEn: "Find Chef Hoyun's dishes with what you have!",
    youtubeUrl: "https://www.youtube.com/@chefhoyoon",
    instagramUrl: "https://www.instagram.com/chefhoyoon/",
  },
  "미뇨끼": {
    slug: "minyokki",
    displayName: "미뇨끼",
    heroTitle: "미뇨끼의 레시피\n재료로 바로 찾기",
    heroSubtitle: "내 재료로 미뇨끼의 요리를 찾아보세요!",
    heroTitleEn: "Minyokki's Recipes\nFind by Ingredients",
    heroSubtitleEn: "Find Minyokki's dishes with what you have!",
    youtubeUrl: "https://www.youtube.com/@미뇨끼",
    instagramUrl: "https://www.instagram.com/minyo_kki/",
  },
  "1분다이어터 1mindiet": {
    slug: "1mindiet",
    displayName: "1분다이어터",
    heroTitle: "1분다이어터의 레시피\n재료로 바로 찾기",
    heroSubtitle: "내 재료로 1분다이어터의 요리를 찾아보세요!",
    heroTitleEn: "1mindiet's Recipes\nFind by Ingredients",
    heroSubtitleEn: "Find 1mindiet's dishes with what you have!",
    youtubeUrl: "https://www.youtube.com/@1mindiet",
  },
  "강레오 걍레오": {
    slug: "leokang",
    displayName: "강레오",
    heroTitle: "강레오의 레시피\n재료로 바로 찾기",
    heroSubtitle: "내 재료로 강레오의 요리를 찾아보세요!",
    heroTitleEn: "Gangreo's Recipes\nFind by Ingredients",
    heroSubtitleEn: "Find Gangreo's dishes with what you have!",
    youtubeUrl: "https://www.youtube.com/@justleo55",
    instagramUrl: "https://www.instagram.com/justleo_official/",
  },
  "한신희": {
    slug: "shinheecal",
    displayName: "한신희",
    heroTitle: "한신희의 레시피\n재료로 바로 찾기",
    heroSubtitle: "내 재료로 한신희의 요리를 찾아보세요!",
    heroTitleEn: "Shinhee's Recipes\nFind by Ingredients",
    heroSubtitleEn: "Find Shinhee's dishes with what you have!",
    youtubeUrl: "https://www.youtube.com/@shinheecal",
    instagramUrl: "https://www.instagram.com/_xinhann/",
  },
  "김밀란": {
    slug: "kimmilan",
    displayName: "김밀란",
    heroTitle: "김밀란의 레시피\n재료로 바로 찾기",
    heroSubtitle: "내 재료로 김밀란의 요리를 찾아보세요!",
    heroTitleEn: "Kimmilan's Recipes\nFind by Ingredients",
    heroSubtitleEn: "Find Kimmilan's dishes with what you have!",
    youtubeUrl: "https://www.youtube.com/@Kimmilan",
    instagramUrl: "https://www.instagram.com/milan__kim/",
  },
};

export default chefConfig;
